default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ramen_development

test:
  <<: *default
  database: ramen_test

#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: ramen_production
  username: ramen
  password: <%= ENV['RAMEN_DATABASE_PASSWORD'] %>
